---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postings
  namespace: postings
subjects:
- kind: ServiceAccount
  name: image-puller
  apiGroup: ""
roleRef:
  kind: Role 
  name: postings
  apiGroup: rbac.authorization.k8s.io
